export const routes = {
  marketing: {
    home: "/",
  },
  auth: {
    register: "/auth/register",
    login: "/auth/login",
  },
  brandAuth: {
    register: "/brand/auth/register",
    login: "/brand/auth/login",
    forgotPassword: "/brand/auth/forgot-password",
  },
  onboarding: "/onboarding",
  user: {
    home: "/app",
    challenges: "/app/challenges",
    brands: "/app/brands",
    myChallenges: "/app/my-challenges",
    favorites: "/app/favorites",
    rewards: "/app/rewards",
    brandDetail: (id: string) => `/app/brands/${encodeURIComponent(id)}`,
    challengeDetail: (id: string) => `/app/challenges/${id}`,
    map: "/app/map",
    profile: "/app/profile",
    coins: "/app/coins",
    coinsHistory: "/app/coins/history",
  },
  brand: {
    dashboard: "/brand",
    challenges: "/brand/challenges",
    newChallenge: "/brand/challenges/new",
    analytics: "/brand/analytics",
    rewards: "/brand/rewards",
    scanner: "/brand/scanner",
    scanResult: "/brand/scan-result",
    preview: "/brand/preview",
    locations: "/brand/locations",
    settings: "/brand/settings",
  },
} as const;
