import { NextResponse } from "next/server";
import { canManageLocationCampaigns, locationUnauthorized, requireLocationSession } from "@/lib/location-auth";
import { prisma } from "@/lib/prisma";
import { getRewardPayload, validateRewardPayload } from "@/lib/brand-reward-validation";

async function owned(id: string, brandId: string, locationId: string) { return prisma.brandReward.findFirst({ where: { id, brandId, locationId } }); }
export async function GET(_request: Request, context: RouteContext<"/api/location/rewards/[id]">) { const session = await requireLocationSession(); if (!session) return locationUnauthorized(); if (!canManageLocationCampaigns(session)) return NextResponse.json({ error: "Недостаточно прав." }, { status: 403 }); const { id } = await context.params; const reward = await owned(id, session.brand.id, session.location.id); return reward ? NextResponse.json({ reward }) : NextResponse.json({ error: "Награда не найдена." }, { status: 404 }); }
export async function PATCH(request: Request, context: RouteContext<"/api/location/rewards/[id]">) { const session = await requireLocationSession(); if (!session) return locationUnauthorized(); if (!canManageLocationCampaigns(session)) return NextResponse.json({ error: "Недостаточно прав." }, { status: 403 }); const { id } = await context.params; if (!(await owned(id, session.brand.id, session.location.id))) return NextResponse.json({ error: "Награда не найдена." }, { status: 404 }); const body = await request.json().catch(() => null) as Record<string, unknown> | null; if (body?.archive === true || body?.action === "archive") { const reward = await prisma.brandReward.update({ where: { id }, data: { status: "archived", archivedAt: new Date() } }); return NextResponse.json({ reward }); } const payload = getRewardPayload(body); const error = validateRewardPayload(payload); if (error) return NextResponse.json({ error }, { status: 400 }); const reward = await prisma.brandReward.update({ where: { id }, data: { title: payload.title, type: payload.type, description: payload.description, limit: payload.limit, points: payload.points, expiresInDays: payload.expiresInDays, usageTerms: payload.usageTerms } }); return NextResponse.json({ reward }); }
export async function DELETE(_request: Request, context: RouteContext<"/api/location/rewards/[id]">) { const session = await requireLocationSession(); if (!session) return locationUnauthorized(); if (!canManageLocationCampaigns(session)) return NextResponse.json({ error: "Недостаточно прав." }, { status: 403 }); const { id } = await context.params; if (!(await owned(id, session.brand.id, session.location.id))) return NextResponse.json({ error: "Награда не найдена." }, { status: 404 }); const reward = await prisma.brandReward.update({ where: { id }, data: { status: "archived", archivedAt: new Date() } }); return NextResponse.json({ reward }); }
