import bcrypt from "bcryptjs";
import { NextResponse } from "next/server";
import { getCurrentBrand } from "@/lib/auth-server";
import { normalizeIdentifier } from "@/lib/auth-shared";
import { prisma } from "@/lib/prisma";
export const runtime = "nodejs";
async function owned(id: string, brandId: string) { return prisma.brandLocation.findFirst({ where: { id, brandId } }); }
export async function POST(request: Request, context: RouteContext<"/api/brand/locations/[id]/location-admin">) { const session = await getCurrentBrand(); if (!session) return NextResponse.json({ error: "Требуется вход бренда." }, { status: 401 }); const { id } = await context.params; if (!await owned(id, session.brand.id)) return NextResponse.json({ error: "Точка не найдена." }, { status: 404 }); const body = await request.json().catch(() => null) as { name?: string; email?: string; password?: string; passwordConfirmation?: string } | null; const name = body?.name?.trim() ?? ""; const email = normalizeIdentifier(body?.email ?? ""); if (!name || !email.includes("@") || !body?.password || body.password.length < 6 || body.password !== body.passwordConfirmation) return NextResponse.json({ error: "Заполните корректные данные администратора точки." }, { status: 400 }); if (await prisma.locationUser.findUnique({ where: { email } })) return NextResponse.json({ error: "Этот email уже используется." }, { status: 409 }); const user = await prisma.locationUser.create({ data: { brandId: session.brand.id, locationId: id, name, email, passwordHash: await bcrypt.hash(body.password, 12), role: "LOCATION_ADMIN" }, select: { id: true, name: true, email: true, status: true } }); return NextResponse.json({ admin: user }, { status: 201 }); }
export async function PATCH(request: Request, context: RouteContext<"/api/brand/locations/[id]/location-admin">) { const session = await getCurrentBrand(); if (!session) return NextResponse.json({ error: "Требуется вход бренда." }, { status: 401 }); const { id } = await context.params; if (!await owned(id, session.brand.id)) return NextResponse.json({ error: "Точка не найдена." }, { status: 404 }); const admin = await prisma.locationUser.findFirst({ where: { locationId: id, role: "LOCATION_ADMIN" } }); if (!admin) return NextResponse.json({ error: "Администратор точки не назначен." }, { status: 404 }); const body = await request.json().catch(() => null) as { status?: "ACTIVE" | "DISABLED"; password?: string; passwordConfirmation?: string } | null; if (body?.password && (body.password.length < 6 || body.password !== body.passwordConfirmation)) return NextResponse.json({ error: "Пароли не совпадают или слишком короткие." }, { status: 400 }); const updated = await prisma.locationUser.update({ where: { id: admin.id }, data: { ...(body?.status ? { status: body.status } : {}), ...(body?.password ? { passwordHash: await bcrypt.hash(body.password, 12) } : {}) }, select: { id: true, name: true, email: true, status: true } }); return NextResponse.json({ admin: updated }); }
