import { notFound, redirect } from "next/navigation";
import { NewChallengeWizard } from "@/app/brand/(cabinet)/challenges/new/new-challenge-wizard";
import { LocationChallengeActions } from "@/components/location/location-challenge-actions";
import { getCurrentLocationSession } from "@/lib/auth-server";
import type { BrandChallengeDto } from "@/lib/brand-challenges";
import type { BrandRewardDto, BrandRewardStatus, BrandRewardType } from "@/lib/brand-rewards";
import { prisma } from "@/lib/prisma";
import { routes } from "@/lib/routes";

type ChallengeView = { id: string; title: string; description: string | null; status: string; category: string | null; mechanicType: string | null; mechanicParams: unknown; reward: string | null; rewardData: unknown; startsAt: Date | null; endsAt: Date | null; createdAt: Date; source?: string; createdByLocationUserId?: string | null; type?: string | null; heroImageUrl?: string | null; locationIds?: string[]; scheduledAt?: Date | null; publishedAt?: Date | null; updatedAt: Date };
function rewardDto(item: { id:string;title:string;type:string;description:string;status:string;limit:number|null;points:number;expiresInDays:number|null;usageTerms:string|null;issuedCount:number;redeemedCount:number;archivedAt:Date|null;createdAt:Date;updatedAt:Date }): BrandRewardDto { return { ...item, type:item.type as BrandRewardType, status:item.status as BrandRewardStatus, archivedAt:item.archivedAt?.toISOString() ?? null, createdAt:item.createdAt.toISOString(),updatedAt:item.updatedAt.toISOString() }; }
function dto(item: ChallengeView): BrandChallengeDto { return { id:item.id,brandId:"",source:item.source ?? "location",createdByLocationUserId:item.createdByLocationUserId ?? null,title:item.title,description:item.description ?? "",status:item.status as BrandChallengeDto["status"],type:item.type ?? item.category,category:item.category,mechanicType:item.mechanicType,mechanicParams:item.mechanicParams as BrandChallengeDto["mechanicParams"],reward:item.reward,rewardData:item.rewardData as BrandChallengeDto["rewardData"],heroImageUrl:item.heroImageUrl ?? null,locationIds:item.locationIds ?? [],startsAt:item.startsAt?.toISOString() ?? null,endsAt:item.endsAt?.toISOString() ?? null,scheduledAt:item.scheduledAt?.toISOString() ?? null,publishedAt:item.publishedAt?.toISOString() ?? null,createdAt:item.createdAt.toISOString(),updatedAt:item.updatedAt.toISOString() }; }
function Details({ item, brand, location, mode, source, comment }: { item: ChallengeView; brand:string;location:string;mode:string;source:string;comment?:string|null }) { const reward=item.reward ?? (item.rewardData && typeof item.rewardData==="object" && "title" in item.rewardData ? String((item.rewardData as {title?:unknown}).title ?? "—") : "—"); return <section className="mx-auto w-full max-w-[1280px] px-6 pt-6"><div className="rounded-3xl border border-slate-200 bg-white p-6"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm font-bold text-blue-700">{source}</p><h1 className="mt-1 text-3xl font-black">{item.title}</h1></div><span className="h-fit rounded-full bg-slate-100 px-3 py-1 text-sm font-black">{item.status || "Без статуса"}</span></div>{source==="Создан КБ"?<p className="mt-5 rounded-2xl bg-slate-50 p-4 text-sm font-bold text-slate-600">Этот челлендж создан основным кабинетом бренда. В кабинете точки его можно только просматривать.</p>:null}<dl className="mt-6 grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-3"><div><dt className="text-slate-400">Бренд</dt><dd className="mt-1 font-bold">{brand}</dd></div><div><dt className="text-slate-400">Точка · режим</dt><dd className="mt-1 font-bold">{location} · {mode}</dd></div><div><dt className="text-slate-400">Создан</dt><dd className="mt-1 font-bold">{item.createdAt.toLocaleDateString("ru-RU")}</dd></div><div><dt className="text-slate-400">Награда</dt><dd className="mt-1 font-bold">{reward}</dd></div><div><dt className="text-slate-400">Сроки</dt><dd className="mt-1 font-bold">{item.startsAt || item.endsAt ? `${item.startsAt?.toLocaleDateString("ru-RU") ?? "—"} — ${item.endsAt?.toLocaleDateString("ru-RU") ?? "—"}` : "Не указаны"}</dd></div><div><dt className="text-slate-400">Условия</dt><dd className="mt-1 font-bold">{item.mechanicType ?? item.category ?? "Не указаны"}</dd></div></dl><div className="mt-6"><p className="text-sm font-bold text-slate-400">Описание</p><p className="mt-2 leading-7 text-slate-600">{item.description || "Описание не указано."}</p></div>{comment?<p className="mt-5 rounded-2xl bg-amber-50 p-4 text-sm font-bold text-amber-900">Комментарий КБ: {comment}</p>:null}</div></section>; }
export default async function LocationChallengeDetail({params}:PageProps<"/location/challenges/[id]">){const session=await getCurrentLocationSession();if(!session)redirect("/brand/auth/login?mode=location");if(session.user.role!=="LOCATION_ADMIN"||session.location.mode==="STANDARD")redirect(routes.location.dashboard);const {id}=await params;const location={id:session.location.id,title:session.location.name??"Точка",address:session.location.fullAddress??session.location.address,district:session.location.city};if(session.location.mode==="EXTENDED"){const request=await prisma.locationChallengeRequest.findFirst({where:{id,brandId:session.brand.id,locationId:session.location.id}});if(!request)notFound();const item={...request,reward:null,updatedAt:request.updatedAt} as ChallengeView;const editable=["draft","changes_requested","rejected"].includes(request.status);if(!editable)return <Details item={item} brand={session.brand.name} location={location.title} mode="Extended" source="Заявка точки" comment={request.brandReviewComment}/>;const rewards=await prisma.brandReward.findMany({where:{brandId:session.brand.id,OR:[{locationId:session.location.id},{locationId:null,source:"brand"}],status:{not:"archived"}}});return <><Details item={item} brand={session.brand.name} location={location.title} mode="Extended" source="Заявка точки" comment={request.brandReviewComment}/><NewChallengeWizard brandLogo={session.brand.logoUrl} brandName={session.brand.name} initialChallenge={dto(item)} locations={[location]} rewards={rewards.map(rewardDto)} locationScope={{mode:"EXTENDED",locationName:location.title}}/></>;}const challenge=await prisma.brandChallenge.findFirst({where:{id,brandId:session.brand.id,locationIds:{has:session.location.id}}});if(!challenge)notFound();const item=challenge as ChallengeView;if(challenge.source!=="location")return <Details item={item} brand={session.brand.name} location={location.title} mode="Flagship" source="Создан КБ"/>;const rewards=await prisma.brandReward.findMany({where:{brandId:session.brand.id,OR:[{locationId:session.location.id},{locationId:null,source:"brand"}],status:{not:"archived"}}});return <><Details item={item} brand={session.brand.name} location={location.title} mode="Flagship" source="Создан точкой"/><div className="mx-auto w-full max-w-[1280px] px-6 pt-3"><LocationChallengeActions id={challenge.id} status={challenge.status}/></div><NewChallengeWizard brandLogo={session.brand.logoUrl} brandName={session.brand.name} initialChallenge={dto(item)} locations={[location]} rewards={rewards.map(rewardDto)} locationScope={{mode:"FLAGSHIP",locationName:location.title}}/></>;}
